spring:
  application:
    name: assessment

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            audience: ${AUTH0_AUDIENCE}
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}
